/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import menu.RestaurantQueue.lib.shopcenter;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.*;
import java.util.List;
import lib.*;
import javax.swing.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.util.ArrayList;

/**
 *
 * @author ACER
 */
public class MenuListFrame extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuListFrame.class.getName());
    private shopcenter shop = new shopcenter();
    private MenuItemPanel selectedItemPanel = null; 
 
    
    /**
     * Creates new form MenuListFrame1
     */
    public MenuListFrame() {
        initComponents();
        SelectBox.setSelectedIndex(0);
        loadMenu("src\\menu\\RestaurantQueue\\Drinks.txt");
        loadMenu("src\\menu\\RestaurantQueue\\Dessert.txt");
        loadMenu("src\\menu\\RestaurantQueue\\Maincourse.txt");
        this.setLocationRelativeTo(null); 
    }
    public void onMenuSelected(MenuItemPanel selectedPanel, boolean isSelected) {
    if (isSelected) {
        if (selectedItemPanel != null && selectedItemPanel != selectedPanel) {
            selectedItemPanel.setSelected(false); 
        }
        selectedItemPanel = selectedPanel;
    } else if (selectedItemPanel == selectedPanel) {
        selectedItemPanel = null;
        }
    }
    private void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Head = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Homebutton = new javax.swing.JButton();
        AddToStockBtn = new javax.swing.JButton();
        DeleteMenu = new javax.swing.JButton();
        Left = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        btnMain = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        btnDrinks = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        btnDessert = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        btnNewMenu = new javax.swing.JButton();
        MidScroll = new javax.swing.JScrollPane();
        CardPanel = new javax.swing.JPanel();
        DrinkPanel = new javax.swing.JPanel();
        MainPanel = new javax.swing.JPanel();
        DessertPanel = new javax.swing.JPanel();
        NewMenuPanel = new javax.swing.JPanel();
        FoodDetailPanel = new javax.swing.JPanel();
        TypePanel = new javax.swing.JPanel();
        TypeLabel = new javax.swing.JLabel();
        TypeComboPanel = new javax.swing.JPanel();
        SelectBox = new javax.swing.JComboBox<>();
        jPanel14 = new javax.swing.JPanel();
        IDPanel = new javax.swing.JPanel();
        IDLabel = new javax.swing.JLabel();
        IDtxtPanel = new javax.swing.JPanel();
        txtID = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        NamePanel = new javax.swing.JPanel();
        NameLabel = new javax.swing.JLabel();
        NametxtPanel = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        jPanel29 = new javax.swing.JPanel();
        PricePanel = new javax.swing.JPanel();
        PriceLabel = new javax.swing.JLabel();
        PricetxtPanel = new javax.swing.JPanel();
        txtPrice = new javax.swing.JTextField();
        BahtPanel = new javax.swing.JPanel();
        BahtLabel = new javax.swing.JLabel();
        ImagePanel = new javax.swing.JPanel();
        ImageLabel = new javax.swing.JLabel();
        ImagetxtPanel = new javax.swing.JPanel();
        txtImage = new javax.swing.JTextField();
        ImportPanel = new javax.swing.JPanel();
        btnImport = new javax.swing.JButton();
        jPanel37 = new javax.swing.JPanel();
        ChoosePanel = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        btnClear = new javax.swing.JButton();
        jPanel40 = new javax.swing.JPanel();
        btnADD = new javax.swing.JButton();
        jPanel39 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1400, 800));

        Head.setBackground(new java.awt.Color(234, 198, 167));
        Head.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(133, 143, 180));

        Homebutton.setBackground(new java.awt.Color(153, 153, 255));
        Homebutton.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        Homebutton.setForeground(new java.awt.Color(255, 255, 255));
        Homebutton.setText("Home");
        Homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomebuttonActionPerformed(evt);
            }
        });

        AddToStockBtn.setBackground(new java.awt.Color(153, 153, 255));
        AddToStockBtn.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        AddToStockBtn.setForeground(new java.awt.Color(255, 255, 255));
        AddToStockBtn.setText("Add to Stock");
        AddToStockBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToStockBtnActionPerformed(evt);
            }
        });

        DeleteMenu.setBackground(new java.awt.Color(204, 204, 255));
        DeleteMenu.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        DeleteMenu.setForeground(new java.awt.Color(102, 102, 255));
        DeleteMenu.setText("Delete Menu");
        DeleteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Homebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 756, Short.MAX_VALUE)
                .addComponent(DeleteMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddToStockBtn)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AddToStockBtn)
                        .addComponent(DeleteMenu))
                    .addComponent(Homebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Head.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(Head, java.awt.BorderLayout.PAGE_START);

        Left.setBackground(new java.awt.Color(196, 195, 227));
        Left.setLayout(new java.awt.GridLayout(4, 0));

        jPanel10.setBackground(new java.awt.Color(204, 209, 219));

        btnMain.setBackground(new java.awt.Color(204, 209, 219));
        btnMain.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnMain.setForeground(new java.awt.Color(101, 112, 154));
        btnMain.setText("   Main course");
        btnMain.setBorder(null);
        btnMain.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(btnMain, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );

        Left.add(jPanel10);

        jPanel11.setBackground(new java.awt.Color(204, 209, 219));

        btnDrinks.setBackground(new java.awt.Color(204, 209, 219));
        btnDrinks.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnDrinks.setForeground(new java.awt.Color(101, 112, 154));
        btnDrinks.setText("   Drinks");
        btnDrinks.setBorder(null);
        btnDrinks.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrinksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnDrinks, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnDrinks, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );

        Left.add(jPanel11);

        jPanel12.setBackground(new java.awt.Color(204, 209, 219));

        btnDessert.setBackground(new java.awt.Color(204, 209, 219));
        btnDessert.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnDessert.setForeground(new java.awt.Color(101, 112, 154));
        btnDessert.setText("   Dessert");
        btnDessert.setBorder(null);
        btnDessert.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDessert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDessertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(btnDessert, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnDessert, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addGap(37, 37, 37))
        );

        Left.add(jPanel12);

        jPanel13.setBackground(new java.awt.Color(204, 209, 219));

        btnNewMenu.setBackground(new java.awt.Color(153, 153, 255));
        btnNewMenu.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnNewMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnNewMenu.setText("   New Menu");
        btnNewMenu.setBorder(null);
        btnNewMenu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNewMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(btnNewMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnNewMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addGap(58, 58, 58))
        );

        Left.add(jPanel13);

        getContentPane().add(Left, java.awt.BorderLayout.LINE_START);

        MidScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        CardPanel.setLayout(new java.awt.CardLayout());

        DrinkPanel.setBackground(new java.awt.Color(204, 209, 219));
        DrinkPanel.setLayout(new java.awt.GridLayout(0, 3, 5, 5));
        CardPanel.add(DrinkPanel, "card3");

        MainPanel.setBackground(new java.awt.Color(204, 209, 219));
        MainPanel.setLayout(new java.awt.GridLayout(0, 3, 5, 5));
        CardPanel.add(MainPanel, "card4");

        DessertPanel.setBackground(new java.awt.Color(204, 209, 219));
        DessertPanel.setLayout(new java.awt.GridLayout(0, 3, 5, 5));
        CardPanel.add(DessertPanel, "card2");

        FoodDetailPanel.setBackground(new java.awt.Color(255, 255, 255));
        FoodDetailPanel.setPreferredSize(new java.awt.Dimension(931, 423));
        FoodDetailPanel.setLayout(new java.awt.GridLayout(6, 3));

        TypePanel.setBackground(new java.awt.Color(255, 255, 255));

        TypeLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        TypeLabel.setText("Type:");

        javax.swing.GroupLayout TypePanelLayout = new javax.swing.GroupLayout(TypePanel);
        TypePanel.setLayout(TypePanelLayout);
        TypePanelLayout.setHorizontalGroup(
            TypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TypePanelLayout.createSequentialGroup()
                .addContainerGap(214, Short.MAX_VALUE)
                .addComponent(TypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TypePanelLayout.setVerticalGroup(
            TypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TypePanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(TypeLabel)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        FoodDetailPanel.add(TypePanel);

        TypeComboPanel.setBackground(new java.awt.Color(255, 255, 255));

        SelectBox.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        SelectBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type", "Maincourse", "Drinks", "Dessert" }));
        SelectBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TypeComboPanelLayout = new javax.swing.GroupLayout(TypeComboPanel);
        TypeComboPanel.setLayout(TypeComboPanelLayout);
        TypeComboPanelLayout.setHorizontalGroup(
            TypeComboPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TypeComboPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SelectBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        TypeComboPanelLayout.setVerticalGroup(
            TypeComboPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TypeComboPanelLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(SelectBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        FoodDetailPanel.add(TypeComboPanel);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 82, Short.MAX_VALUE)
        );

        FoodDetailPanel.add(jPanel14);

        IDPanel.setBackground(new java.awt.Color(255, 255, 255));

        IDLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        IDLabel.setText("ID:");

        javax.swing.GroupLayout IDPanelLayout = new javax.swing.GroupLayout(IDPanel);
        IDPanel.setLayout(IDPanelLayout);
        IDPanelLayout.setHorizontalGroup(
            IDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IDPanelLayout.createSequentialGroup()
                .addContainerGap(214, Short.MAX_VALUE)
                .addComponent(IDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        IDPanelLayout.setVerticalGroup(
            IDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IDPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(IDLabel)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        FoodDetailPanel.add(IDPanel);

        IDtxtPanel.setBackground(new java.awt.Color(255, 255, 255));

        txtID.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N

        javax.swing.GroupLayout IDtxtPanelLayout = new javax.swing.GroupLayout(IDtxtPanel);
        IDtxtPanel.setLayout(IDtxtPanelLayout);
        IDtxtPanelLayout.setHorizontalGroup(
            IDtxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IDtxtPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        IDtxtPanelLayout.setVerticalGroup(
            IDtxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IDtxtPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        FoodDetailPanel.add(IDtxtPanel);

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 82, Short.MAX_VALUE)
        );

        FoodDetailPanel.add(jPanel23);

        NamePanel.setBackground(new java.awt.Color(255, 255, 255));

        NameLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        NameLabel.setText("Name:");

        javax.swing.GroupLayout NamePanelLayout = new javax.swing.GroupLayout(NamePanel);
        NamePanel.setLayout(NamePanelLayout);
        NamePanelLayout.setHorizontalGroup(
            NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NamePanelLayout.createSequentialGroup()
                .addContainerGap(214, Short.MAX_VALUE)
                .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        NamePanelLayout.setVerticalGroup(
            NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NamePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(NameLabel)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        FoodDetailPanel.add(NamePanel);

        NametxtPanel.setBackground(new java.awt.Color(255, 255, 255));

        txtName.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N

        javax.swing.GroupLayout NametxtPanelLayout = new javax.swing.GroupLayout(NametxtPanel);
        NametxtPanel.setLayout(NametxtPanelLayout);
        NametxtPanelLayout.setHorizontalGroup(
            NametxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NametxtPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NametxtPanelLayout.setVerticalGroup(
            NametxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NametxtPanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        FoodDetailPanel.add(NametxtPanel);

        jPanel29.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 82, Short.MAX_VALUE)
        );

        FoodDetailPanel.add(jPanel29);

        PricePanel.setBackground(new java.awt.Color(255, 255, 255));

        PriceLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        PriceLabel.setText("Price:");

        javax.swing.GroupLayout PricePanelLayout = new javax.swing.GroupLayout(PricePanel);
        PricePanel.setLayout(PricePanelLayout);
        PricePanelLayout.setHorizontalGroup(
            PricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PricePanelLayout.createSequentialGroup()
                .addContainerGap(214, Short.MAX_VALUE)
                .addComponent(PriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PricePanelLayout.setVerticalGroup(
            PricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PricePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(PriceLabel)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        FoodDetailPanel.add(PricePanel);

        PricetxtPanel.setBackground(new java.awt.Color(255, 255, 255));

        txtPrice.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N

        javax.swing.GroupLayout PricetxtPanelLayout = new javax.swing.GroupLayout(PricetxtPanel);
        PricetxtPanel.setLayout(PricetxtPanelLayout);
        PricetxtPanelLayout.setHorizontalGroup(
            PricetxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PricetxtPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PricetxtPanelLayout.setVerticalGroup(
            PricetxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PricetxtPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        FoodDetailPanel.add(PricetxtPanel);

        BahtPanel.setBackground(new java.awt.Color(255, 255, 255));

        BahtLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        BahtLabel.setText("Baht");

        javax.swing.GroupLayout BahtPanelLayout = new javax.swing.GroupLayout(BahtPanel);
        BahtPanel.setLayout(BahtPanelLayout);
        BahtPanelLayout.setHorizontalGroup(
            BahtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BahtPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BahtLabel)
                .addContainerGap(259, Short.MAX_VALUE))
        );
        BahtPanelLayout.setVerticalGroup(
            BahtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BahtPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(BahtLabel)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        FoodDetailPanel.add(BahtPanel);

        ImagePanel.setBackground(new java.awt.Color(255, 255, 255));

        ImageLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        ImageLabel.setText("Image:");

        javax.swing.GroupLayout ImagePanelLayout = new javax.swing.GroupLayout(ImagePanel);
        ImagePanel.setLayout(ImagePanelLayout);
        ImagePanelLayout.setHorizontalGroup(
            ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ImagePanelLayout.createSequentialGroup()
                .addContainerGap(214, Short.MAX_VALUE)
                .addComponent(ImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ImagePanelLayout.setVerticalGroup(
            ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImagePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(ImageLabel)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        FoodDetailPanel.add(ImagePanel);

        ImagetxtPanel.setBackground(new java.awt.Color(255, 255, 255));

        txtImage.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N

        javax.swing.GroupLayout ImagetxtPanelLayout = new javax.swing.GroupLayout(ImagetxtPanel);
        ImagetxtPanel.setLayout(ImagetxtPanelLayout);
        ImagetxtPanelLayout.setHorizontalGroup(
            ImagetxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImagetxtPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtImage, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ImagetxtPanelLayout.setVerticalGroup(
            ImagetxtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImagetxtPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        FoodDetailPanel.add(ImagetxtPanel);

        ImportPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnImport.setBackground(new java.awt.Color(133, 143, 180));
        btnImport.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnImport.setText("Import");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ImportPanelLayout = new javax.swing.GroupLayout(ImportPanel);
        ImportPanel.setLayout(ImportPanelLayout);
        ImportPanelLayout.setHorizontalGroup(
            ImportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnImport)
                .addContainerGap(209, Short.MAX_VALUE))
        );
        ImportPanelLayout.setVerticalGroup(
            ImportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImportPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnImport)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        FoodDetailPanel.add(ImportPanel);

        jPanel37.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 82, Short.MAX_VALUE)
        );

        FoodDetailPanel.add(jPanel37);

        ChoosePanel.setBackground(new java.awt.Color(255, 255, 255));
        ChoosePanel.setLayout(new java.awt.GridLayout(1, 0));

        jPanel41.setBackground(new java.awt.Color(255, 255, 255));

        btnClear.setFont(new java.awt.Font("Tw Cen MT", 1, 30)); // NOI18N
        btnClear.setForeground(new java.awt.Color(204, 0, 0));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel41Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnClear)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel41Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnClear)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        ChoosePanel.add(jPanel41);

        jPanel40.setBackground(new java.awt.Color(255, 255, 255));

        btnADD.setBackground(new java.awt.Color(228, 179, 0));
        btnADD.setFont(new java.awt.Font("Tw Cen MT", 1, 30)); // NOI18N
        btnADD.setForeground(new java.awt.Color(255, 255, 255));
        btnADD.setText("ADD");
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel40Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(btnADD, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel40Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnADD)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        ChoosePanel.add(jPanel40);

        FoodDetailPanel.add(ChoosePanel);

        jPanel39.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
        jPanel39.setLayout(jPanel39Layout);
        jPanel39Layout.setHorizontalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        jPanel39Layout.setVerticalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 82, Short.MAX_VALUE)
        );

        FoodDetailPanel.add(jPanel39);

        javax.swing.GroupLayout NewMenuPanelLayout = new javax.swing.GroupLayout(NewMenuPanel);
        NewMenuPanel.setLayout(NewMenuPanelLayout);
        NewMenuPanelLayout.setHorizontalGroup(
            NewMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
            .addGroup(NewMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(FoodDetailPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE))
        );
        NewMenuPanelLayout.setVerticalGroup(
            NewMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
            .addGroup(NewMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(FoodDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE))
        );

        CardPanel.add(NewMenuPanel, "card5");

        MidScroll.setViewportView(CardPanel);

        getContentPane().add(MidScroll, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainActionPerformed
        CardPanel.removeAll();
        CardPanel.add(MainPanel);
        CardPanel.repaint();
        CardPanel.revalidate();
    }//GEN-LAST:event_btnMainActionPerformed

    private void btnDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrinksActionPerformed
        CardPanel.removeAll();
        CardPanel.add(DrinkPanel);
        CardPanel.repaint();
        CardPanel.revalidate();
    }//GEN-LAST:event_btnDrinksActionPerformed

    private void btnDessertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDessertActionPerformed
        CardPanel.removeAll();
        CardPanel.add(DessertPanel);
        CardPanel.repaint();
        CardPanel.revalidate();
    }//GEN-LAST:event_btnDessertActionPerformed

    private void btnNewMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewMenuActionPerformed
        CardPanel.removeAll();
        CardPanel.add(NewMenuPanel);
        CardPanel.repaint();
        CardPanel.revalidate();
    }//GEN-LAST:event_btnNewMenuActionPerformed

    private void SelectBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectBoxActionPerformed
        
    }//GEN-LAST:event_SelectBoxActionPerformed

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Images (JPG, PNG, GIF)", "jpg", "png", "gif"));
        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            java.io.File selectedFile = fileChooser.getSelectedFile();
            txtImage.setText(selectedFile.getAbsolutePath());
        } else {
            txtImage.setText("");
        }
    }//GEN-LAST:event_btnImportActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtID.setText("");
        txtName.setText("");
        txtPrice.setText("");
        txtImage.setText("");
        SelectBox.setSelectedIndex(0);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed
        try {
            Object selectedObject = SelectBox.getSelectedItem();
            String Id = txtID.getText();
            String Name = txtName.getText();
            String priceText = txtPrice.getText();

            if(selectedObject == null || Id.isEmpty() || Name.isEmpty() || priceText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please input every informations", "Incorrect", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String type = selectedObject.toString();

            double price = Double.parseDouble(txtPrice.getText());
            String imagePath = txtImage.getText();

            shop.Createmenu(type, Id, Name, price, imagePath);
            lib.food lastedFood = shop.getAllmenu().get(shop.getAllmenu().size() - 1);

            MenuItemPanel itemGUI = new MenuItemPanel(lastedFood, this);
            MenuListFrame allMenuPanel = new MenuListFrame();
            allMenuPanel.add(itemGUI); // Add item to Grid Panel
            allMenuPanel.revalidate();
            allMenuPanel.repaint();

            saveMenu(type, Id, Name, price, imagePath);

            SelectBox.setSelectedIndex(0);
            txtID.setText("");
            txtName.setText("");
            txtPrice.setText("");
            txtImage.setText("");
            
            refreshDisplay(); //refresh panel when get new menu

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this, "Price must be a valid number.", "Input Error", JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.WARNING, "Invalid price input", e);
        } catch (InvalidOperationException e) {

            JOptionPane.showMessageDialog(this, e.getMessage(), "Operation Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, "An unexpected error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, "Unexpected error in ADD button", e);
        }
    }//GEN-LAST:event_btnADDActionPerformed

    private void HomebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomebuttonActionPerformed
        MainDisplay panel = new MainDisplay();
        panel.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_HomebuttonActionPerformed

    private void AddToStockBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToStockBtnActionPerformed
        if (selectedItemPanel == null) {
        JOptionPane.showMessageDialog(this, "Please select a menu item first.", "Selection Error", JOptionPane.ERROR_MESSAGE);
        return;
        }
        food selected = selectedItemPanel.getMenuItem();
        String type = selected.gettype();
        String stockFile;

        if (type.equalsIgnoreCase("Drinks")) {
            stockFile = "src\\menu\\RestaurantQueue\\DrinksStock.txt";
        } else if (type.equalsIgnoreCase("Dessert")) {
            stockFile = "src\\menu\\RestaurantQueue\\DessertStock.txt";
        } else if (type.equalsIgnoreCase("Maincourse")) {
            stockFile = "src\\menu\\RestaurantQueue\\MaincourseStock.txt";
        } else {
            JOptionPane.showMessageDialog(this, "Menu type not recognized. Cannot save to stock file.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String dataLine = String.format("%s,%s,%s,%.2f,%s",type,selected.getId(),selected.getName(),selected.getPrice(),selected.getImagePath()); 

        try (FileWriter fw = new FileWriter(stockFile, true);
             BufferedWriter bw = new BufferedWriter(fw);
             PrintWriter out = new PrintWriter(bw)) {

            out.println(dataLine); 

            JOptionPane.showMessageDialog(this,
                    String.format("Added '%s' to %s", selected.getName(), stockFile),
                    "Success", JOptionPane.INFORMATION_MESSAGE);

            selectedItemPanel.setSelected(false);
            selectedItemPanel = null;

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error writing to file " + stockFile + ": " + ex.getMessage(),
                    "File Error", JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, "Error writing to stock file: " + stockFile, ex);
        }
    }//GEN-LAST:event_AddToStockBtnActionPerformed

    private void DeleteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteMenuActionPerformed
        if (selectedItemPanel == null) {
        JOptionPane.showMessageDialog(this, 
            "Select menu want to delete", 
            "notification", JOptionPane.WARNING_MESSAGE);
        return;
        }
        food itemToDelete = selectedItemPanel.getMenuItem();
        String menuName = itemToDelete.getName();
        try {
            deleteMenu(itemToDelete);
            shop.getAllmenu().remove(itemToDelete); 
            selectedItemPanel = null;
            refreshDisplay(); 
            JOptionPane.showMessageDialog(this, 
                "Delete '" + menuName + "' success", 
                "success", JOptionPane.INFORMATION_MESSAGE);
            } catch (java.io.IOException e) {
            JOptionPane.showMessageDialog(this, "Error to open file: " + e.getMessage(), "error I/O", JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, "Error deleting menu item (File IO)", e);
            } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error to delete : " + e.getMessage(), "error", JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, "Error deleting menu item", e);
            }
    }//GEN-LAST:event_DeleteMenuActionPerformed

    private void loadMenu(String fileName) {
        try (BufferedReader br = new BufferedReader(new FileReader(fileName))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] parts = line.split(",");
                if (parts.length == 5) {
                    String type = parts[0];
                    String id = parts[1];
                    String name = parts[2];
                    double price = Double.parseDouble(parts[3]);
                    String imagePath = parts[4];
                    
                    shop.Createmenu(type, id, name, price, imagePath);
                    food foodItem = shop.getAllmenu().get(shop.getAllmenu().size() - 1);

                    MenuItemPanel itemGUI = new MenuItemPanel(foodItem, this);
                    switch (type.toLowerCase()) {
                        case "maincourse":
                            MainPanel.add(itemGUI);
                            break;
                        case "drinks":
                            DrinkPanel.add(itemGUI);
                            break;
                        case "dessert":
                            DessertPanel.add(itemGUI);
                            break;
                    }        
                }
            }
            this.revalidate();
            this.repaint();

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, 
                "Error reading from file " + fileName + ": " + e.getMessage(), 
                "File Error", JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, "Error reading menu file: " + fileName, e);
          } catch (InvalidOperationException ex) {
                Logger.getLogger(MainDisplay.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
                
    //funtuinSaveFile
    private void saveMenu(String type, String Id, String Name, double price, String imagePath) {
    String fileName;
    //Sort by type
    if (type.equalsIgnoreCase("Drinks")) {
        fileName = "src\\menu\\RestaurantQueue\\Drinks.txt";
    } else if (type.equalsIgnoreCase("Dessert")) {
        fileName = "src\\menu\\RestaurantQueue\\Dessert.txt";
    } else if (type.equalsIgnoreCase("Maincourse")) {
        fileName = "src\\menu\\RestaurantQueue\\Maincourse.txt";
    } else {
        fileName = "menu";
    }
    try (FileWriter fw = new FileWriter(fileName, true);
         BufferedWriter bw = new BufferedWriter(fw);
         PrintWriter out = new PrintWriter(bw)) {

        out.println(type + "," + Id + "," + Name + "," + price + "," + imagePath);
        
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(this, "Error writing to file " + fileName + ": " + ex.getMessage(), "File Error", JOptionPane.ERROR_MESSAGE);
        logger.log(java.util.logging.Level.SEVERE, "Error writing menu to file: " + fileName, ex);
        }
    }
    private void deleteMenu(food itemToDelete) throws FileNotFoundException, IOException{
        String type = itemToDelete.gettype();
        String fileName;
        if (type.equalsIgnoreCase("Drinks")) {
        fileName = "src\\menu\\RestaurantQueue\\Drinks.txt";
        } else if (type.equalsIgnoreCase("Dessert")) {
        fileName = "src\\menu\\RestaurantQueue\\Dessert.txt";
        } else if (type.equalsIgnoreCase("Maincourse")) {
        fileName = "src\\menu\\RestaurantQueue\\Maincourse.txt";
        } else {
        return; 
        }
        File file = new File(fileName);
        List<String> lines = new ArrayList<>();
        String dataToDelete = String.format("%s,%s", itemToDelete.getId(), itemToDelete.getName());

        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
        String line;
        while ((line = br.readLine()) != null) {
            String[] parts = line.split(",", 3); 
            
            if (parts.length >= 3) {
                 String Type = parts[0];
                 String Id = parts[1];
                 String Name = parts[2].split(",", 2)[0]; 
                 if (Type.equalsIgnoreCase(type) && Id.equals(itemToDelete.getId()) && Name.equals(itemToDelete.getName())) {
                    continue;
                 }
            } 
            lines.add(line);
        }
    }//Write all remaining lines back to the file (overwrite).
    try (PrintWriter pw = new PrintWriter(new FileWriter(file, false))) {
        for (String line : lines) {
            pw.println(line);
        }
    }
    }
    
    public void refreshDisplay() {
    MainPanel.removeAll();
    DrinkPanel.removeAll();
    DessertPanel.removeAll();
    loadMenu("src\\menu\\RestaurantQueue\\Drinks.txt");
    loadMenu("src\\menu\\RestaurantQueue\\Dessert.txt");
    loadMenu("src\\menu\\RestaurantQueue\\Maincourse.txt");
    this.revalidate();
    this.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuListFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToStockBtn;
    private javax.swing.JLabel BahtLabel;
    private javax.swing.JPanel BahtPanel;
    private javax.swing.JPanel CardPanel;
    private javax.swing.JPanel ChoosePanel;
    private javax.swing.JButton DeleteMenu;
    private javax.swing.JPanel DessertPanel;
    private javax.swing.JPanel DrinkPanel;
    private javax.swing.JPanel FoodDetailPanel;
    private javax.swing.JPanel Head;
    private javax.swing.JButton Homebutton;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JPanel IDPanel;
    private javax.swing.JPanel IDtxtPanel;
    private javax.swing.JLabel ImageLabel;
    private javax.swing.JPanel ImagePanel;
    private javax.swing.JPanel ImagetxtPanel;
    private javax.swing.JPanel ImportPanel;
    private javax.swing.JPanel Left;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JScrollPane MidScroll;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JPanel NamePanel;
    private javax.swing.JPanel NametxtPanel;
    private javax.swing.JPanel NewMenuPanel;
    private javax.swing.JLabel PriceLabel;
    private javax.swing.JPanel PricePanel;
    private javax.swing.JPanel PricetxtPanel;
    private javax.swing.JComboBox<String> SelectBox;
    private javax.swing.JPanel TypeComboPanel;
    private javax.swing.JLabel TypeLabel;
    private javax.swing.JPanel TypePanel;
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDessert;
    private javax.swing.JButton btnDrinks;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnMain;
    private javax.swing.JButton btnNewMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtImage;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables

    void onMenuSelected(boolean selected) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
