/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;
import lib.*;
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author ACER
 */
public class MenuItemPanel extends javax.swing.JPanel {
    private final food menuItem;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuItemPanel.class.getName());
    private boolean isSelected = false; 
    private MenuListFrame listframe; 
    
    /**
     * Creates new form MenuItemPanel
     */
    public MenuItemPanel(food item,MenuListFrame frame) {
        this.menuItem = item;
        this.listframe = frame;
        initComponents();
        displayFoodDetails();
    }
    
    private void displayFoodDetails() {
        if(menuItem != null) {
            TypeOutput.setText(menuItem.gettype());
            IdOutput.setText(menuItem.getId());
            NameOutput.setText(menuItem.getName());
            PriceOutput.setText(String.format("%.2f", menuItem.getPrice()));
            setImage(menuItem.getImagePath());
        }    
    }

    private void setImage(String imagePath) {
        if (imagePath == null || imagePath.isEmpty()) {
            ImageOutput.setText("No Image");
            return;
        }

        try {
            ImageIcon originalIcon = new ImageIcon(imagePath);
            Image img = originalIcon.getImage();
            
            final int DESIRED_SIZE = 280;

            Image scaledImg = img.getScaledInstance(
                DESIRED_SIZE,
                DESIRED_SIZE,
                Image.SCALE_SMOOTH 
            );
            
            // 4. ตั้งค่า ImageIcon ใหม่ที่ปรับขนาดแล้วให้กับ ImageOutput
            ImageOutput.setIcon(new ImageIcon(scaledImg));
            ImageOutput.setText(""); // ลบข้อความ "No Image" ออก
            
            ImageOutput.setPreferredSize(new java.awt.Dimension(DESIRED_SIZE, DESIRED_SIZE));
            
        } catch (Exception e) {
            // ถ้าโหลดรูปภาพไม่สำเร็จ (เช่น Path ผิด)
            ImageOutput.setIcon(null);
            ImageOutput.setText("Image Load Error: " + e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ImageOutput = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        TypeLabel = new javax.swing.JLabel();
        TypeOutput = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        IdLabel = new javax.swing.JLabel();
        IdOutput = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        NameLabel = new javax.swing.JLabel();
        NameOutput = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        PriceLabel = new javax.swing.JLabel();
        PriceOutput = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(300, 420));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        ImageOutput.setBackground(new java.awt.Color(255, 255, 255));
        ImageOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImageOutput.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImageOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImageOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(4, 0));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        TypeLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        TypeLabel.setText("Type:");

        TypeOutput.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TypeOutput.setText(" ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TypeOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TypeLabel)
                    .addComponent(TypeOutput))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        IdLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        IdLabel.setText("ID:");

        IdOutput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        IdOutput.setText(" ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(IdOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdLabel)
                    .addComponent(IdOutput))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        NameLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        NameLabel.setText("Name:");

        NameOutput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NameOutput.setText(" ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NameOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(NameOutput))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        PriceLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        PriceLabel.setText("Price:");

        PriceOutput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PriceOutput.setText(" ");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel10.setText("Baht");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PriceOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PriceLabel)
                    .addComponent(PriceOutput)
                    .addComponent(jLabel10))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel7);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    public food getMenuItem() {
        return menuItem;
    }
    public boolean isSelected() {
        return isSelected;
    }
    public void setSelected(boolean isSelected){
        isSelected = !isSelected;
        Color selected = new Color(153,153,255); 
        Color unselected = Color.white;
        Color tab; 
        if (isSelected) {
            tab = selected; 
        } else {
            tab = unselected;
        }
        this.setBackground(tab);
        jPanel1.setBackground(tab); 
        jPanel2.setBackground(tab); 
        jPanel3.setBackground(tab); 
        jPanel4.setBackground(tab); 
        jPanel5.setBackground(tab); 
        jPanel6.setBackground(tab); 
        jPanel7.setBackground(tab); 
  
        this.revalidate();
        this.repaint();
        
    } 
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        isSelected = !isSelected;
        Color selected = new Color(153,153,255);
        Color unselected = Color.white;
        Color tab; 
        if (isSelected) {
            tab = selected; 
        } else {
            tab = unselected;
        }
        if (listframe != null) {
        listframe.onMenuSelected(this, isSelected);
    }
        this.setBackground(tab);
        jPanel1.setBackground(tab); 
        jPanel2.setBackground(tab); 
        jPanel3.setBackground(tab); 
        jPanel4.setBackground(tab); 
        jPanel5.setBackground(tab); 
        jPanel6.setBackground(tab); 
        jPanel7.setBackground(tab); 
  
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IdLabel;
    private javax.swing.JLabel IdOutput;
    private javax.swing.JLabel ImageOutput;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel NameOutput;
    private javax.swing.JLabel PriceLabel;
    private javax.swing.JLabel PriceOutput;
    private javax.swing.JLabel TypeLabel;
    private javax.swing.JLabel TypeOutput;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
