
package main;

import javax.swing.*;



/**
 *
 * @author nanth
 */
public class GuiRestaurant extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GuiRestaurant.class.getName());
  
    
    /**
     * Creates new form GuiRestaurant
     */
    public GuiRestaurant() {
        initComponents();
       

 
        setVisible(true);
        setResizable(false);
        setLocationRelativeTo(null); 
        setExtendedState(GuiRestaurant.MAXIMIZED_BOTH); //fullscreen every  run
        
            
    }

    
    public void switchPanel(JPanel newPanel) {
    getContentPane().removeAll();   
    getContentPane().add(newPanel); 
    revalidate();                   
    repaint();                      
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        QueueButton = new java.awt.Button();
        DrinksButton = new java.awt.Button();
        MaincourseButton = new java.awt.Button();
        DessertButton = new java.awt.Button();
        jPanel21 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        CartButton = new javax.swing.JButton();
        jPanel23 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        ExitGui1 = new javax.swing.JButton();
        jPanel26 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        ManagePage = new javax.swing.JPanel();
        QueuePage = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        button5 = new java.awt.Button();
        button6 = new java.awt.Button();
        button7 = new java.awt.Button();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        DrinksPage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MaincoursePage = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        DessertPage = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CartPage = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel29 = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 160));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));
        jPanel6.setAlignmentX(0.0F);
        jPanel6.setAlignmentY(0.0F);
        jPanel6.setMinimumSize(new java.awt.Dimension(375, 30));
        jPanel6.setPreferredSize(new java.awt.Dimension(100, 40));
        java.awt.GridBagLayout jPanel6Layout = new java.awt.GridBagLayout();
        jPanel6Layout.rowHeights = new int[] {50};
        jPanel6.setLayout(jPanel6Layout);

        QueueButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        QueueButton.setLabel("Queue");
        QueueButton.setName(""); // NOI18N
        QueueButton.setPreferredSize(new java.awt.Dimension(50, 25));
        QueueButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QueueButtonMouseClicked(evt);
            }
        });
        QueueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QueueButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 90, 30, 0);
        jPanel6.add(QueueButton, gridBagConstraints);

        DrinksButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        DrinksButton.setLabel("Drinks");
        DrinksButton.setPreferredSize(new java.awt.Dimension(50, 25));
        DrinksButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DrinksButtonMouseClicked(evt);
            }
        });
        DrinksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrinksButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 100, 30, 20);
        jPanel6.add(DrinksButton, gridBagConstraints);

        MaincourseButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        MaincourseButton.setLabel("Maincourse");
        MaincourseButton.setPreferredSize(new java.awt.Dimension(50, 25));
        MaincourseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaincourseButtonMouseClicked(evt);
            }
        });
        MaincourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaincourseButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 60, 30, 70);
        jPanel6.add(MaincourseButton, gridBagConstraints);

        DessertButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        DessertButton.setLabel("Dessert");
        DessertButton.setPreferredSize(new java.awt.Dimension(50, 35));
        DessertButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DessertButtonMouseClicked(evt);
            }
        });
        DessertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DessertButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 95);
        jPanel6.add(DessertButton, gridBagConstraints);

        jPanel2.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel21.setBackground(new java.awt.Color(204, 255, 204));
        jPanel21.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel2.add(jPanel21, java.awt.BorderLayout.PAGE_END);

        jPanel18.setPreferredSize(new java.awt.Dimension(100, 80));
        jPanel18.setLayout(new java.awt.BorderLayout());

        jPanel22.setBackground(new java.awt.Color(255, 255, 204));
        jPanel22.setPreferredSize(new java.awt.Dimension(70, 40));

        CartButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-cart.gif"))); // NOI18N
        CartButton.setBorderPainted(false);
        CartButton.setContentAreaFilled(false);
        CartButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CartButtonMouseClicked(evt);
            }
        });
        CartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addComponent(CartButton, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addComponent(CartButton, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel18.add(jPanel22, java.awt.BorderLayout.LINE_END);

        jPanel23.setBackground(new java.awt.Color(255, 255, 204));
        jPanel23.setForeground(new java.awt.Color(255, 255, 204));
        jPanel23.setPreferredSize(new java.awt.Dimension(140, 40));
        jPanel23.setLayout(null);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-restaurant-40.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel23.add(jButton3);
        jButton3.setBounds(10, 10, 50, 51);

        ExitGui1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-close-sign-40.png"))); // NOI18N
        ExitGui1.setAlignmentY(0.0F);
        ExitGui1.setBorderPainted(false);
        ExitGui1.setContentAreaFilled(false);
        ExitGui1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitGui1ActionPerformed(evt);
            }
        });
        jPanel23.add(ExitGui1);
        ExitGui1.setBounds(60, 10, 50, 51);

        jPanel18.add(jPanel23, java.awt.BorderLayout.LINE_START);

        jPanel26.setBackground(new java.awt.Color(255, 255, 204));

        label1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        label1.setText("Menu");
        jPanel26.add(label1);

        jPanel18.add(jPanel26, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel18, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(40, 100));
        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setForeground(new java.awt.Color(255, 255, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(40, 100));
        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 60));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        ManagePage.setLayout(new java.awt.CardLayout());

        QueuePage.setLayout(new java.awt.BorderLayout());

        jPanel11.setBackground(new java.awt.Color(255, 204, 204));
        jPanel11.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel11.setLayout(new java.awt.GridBagLayout());

        button5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button5.setLabel("Next Queue");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 200, 0, 130);
        jPanel11.add(button5, gridBagConstraints);

        button6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button6.setLabel("Delete");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 130);
        jPanel11.add(button6, gridBagConstraints);

        button7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button7.setLabel("Clear");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 200);
        jPanel11.add(button7, gridBagConstraints);

        QueuePage.add(jPanel11, java.awt.BorderLayout.PAGE_END);

        jPanel12.setPreferredSize(new java.awt.Dimension(30, 100));
        QueuePage.add(jPanel12, java.awt.BorderLayout.LINE_START);

        jPanel13.setPreferredSize(new java.awt.Dimension(30, 100));
        QueuePage.add(jPanel13, java.awt.BorderLayout.LINE_END);

        jPanel14.setPreferredSize(new java.awt.Dimension(100, 30));
        QueuePage.add(jPanel14, java.awt.BorderLayout.PAGE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        QueuePage.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        ManagePage.add(QueuePage, "card2");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Drinks");
        DrinksPage.add(jLabel1);

        ManagePage.add(DrinksPage, "card3");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Maincourse");
        MaincoursePage.add(jLabel2);

        ManagePage.add(MaincoursePage, "card4");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Dessert");
        DessertPage.add(jLabel3);

        ManagePage.add(DessertPage, "card5");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        label2.setBackground(new java.awt.Color(255, 255, 255));
        label2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        label2.setText("Cart");
        jPanel29.add(label2);

        jButton2.setText("next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CartPageLayout = new javax.swing.GroupLayout(CartPage);
        CartPage.setLayout(CartPageLayout);
        CartPageLayout.setHorizontalGroup(
            CartPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CartPageLayout.createSequentialGroup()
                .addContainerGap(425, Short.MAX_VALUE)
                .addGroup(CartPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CartPageLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CartPageLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(51, 51, 51))))
        );
        CartPageLayout.setVerticalGroup(
            CartPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CartPageLayout.createSequentialGroup()
                .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ManagePage.add(CartPage, "card6");

        getContentPane().add(ManagePage, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QueueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QueueButtonActionPerformed
       ManagePage.removeAll();
        ManagePage.add(QueuePage);
        ManagePage.repaint();
        ManagePage.revalidate();
    }//GEN-LAST:event_QueueButtonActionPerformed

    private void DrinksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrinksButtonActionPerformed
        ManagePage.removeAll();
        ManagePage.add(DrinksPage);
        ManagePage.repaint();
        ManagePage.revalidate();
    }//GEN-LAST:event_DrinksButtonActionPerformed

    private void MaincourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaincourseButtonActionPerformed
       ManagePage.removeAll();
        ManagePage.add(MaincoursePage);
        ManagePage.repaint();
        ManagePage.revalidate();
    }//GEN-LAST:event_MaincourseButtonActionPerformed

    private void DessertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DessertButtonActionPerformed
       ManagePage.removeAll();
        ManagePage.add(DessertPage);
        ManagePage.repaint();
        ManagePage.revalidate();
    }//GEN-LAST:event_DessertButtonActionPerformed

    private void QueueButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QueueButtonMouseClicked
        
    }//GEN-LAST:event_QueueButtonMouseClicked

    private void DrinksButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DrinksButtonMouseClicked
     
    }//GEN-LAST:event_DrinksButtonMouseClicked

    private void MaincourseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaincourseButtonMouseClicked
       
    }//GEN-LAST:event_MaincourseButtonMouseClicked

    private void DessertButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DessertButtonMouseClicked
      
    }//GEN-LAST:event_DessertButtonMouseClicked

    private void ExitGui1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitGui1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitGui1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       this.switchPanel(new GuiManageRestaurant());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void CartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CartButtonActionPerformed
      ManagePage.removeAll();
        ManagePage.add(CartPage);
        ManagePage.repaint();
        ManagePage.revalidate();
    }//GEN-LAST:event_CartButtonActionPerformed

    private void CartButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CartButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CartButtonMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new GuiBill().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GuiRestaurant().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CartButton;
    private javax.swing.JPanel CartPage;
    private java.awt.Button DessertButton;
    private javax.swing.JPanel DessertPage;
    private java.awt.Button DrinksButton;
    private javax.swing.JPanel DrinksPage;
    private javax.swing.JButton ExitGui1;
    private java.awt.Button MaincourseButton;
    private javax.swing.JPanel MaincoursePage;
    private javax.swing.JPanel ManagePage;
    private java.awt.Button QueueButton;
    private javax.swing.JPanel QueuePage;
    private java.awt.Button button5;
    private java.awt.Button button6;
    private java.awt.Button button7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}
